version: '3.8'

services:
  cosplay-backend:
    image: cosplaysuggestion-cosplay-backend:latest
    container_name: cosplay-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=aws
    restart: unless-stopped
    networks:
      - cosplay-network

  nginx:
    image: nginx:alpine
    container_name: cosplay-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - cosplay-backend
    restart: unless-stopped
    networks:
      - cosplay-network

networks:
  cosplay-network:
    driver: bridge